[package]
name = "help_my_key"
version = "0.1.0"
authors = ["mindray87 <pa.toth87@gmail.com>"]
edition = "2018"

[[bin]]
name = "passman-daemon"
path = "src/daemon/main.rs"

[[bin]]
name = "passman-cli"
path = "src/cli/main.rs"

[dependencies]
copypasta = "0.7.0"