[package]
name = "help_my_key"
version = "0.1.0"
authors = ["mindray87 <pa.toth87@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
copypasta = "0.7.0"